-- TABELA FREQUENCIA GLOBAL DE FERRAMENTAS (Quais ferramentas são mais requisitadas ao todo? -Considerar o volume total como métrica):
-- CASOS:
---- 
SELECT
    tm.DESTINATIONJOBID AS Obra,
    j.RESPONSIBLEID AS Gestor,
    ti.NAME,
    ROUND(SUM(tmi.QUANTITY), 0) AS VolumeSolicitado,
    CASE 
        WHEN ti.SERIALNUMBER = '' THEN 'NaoSeriada'
        ELSE 'Seriada'
    END AS TipoFerramenta
FROM OSUSR_BBQ_TOOLINGLOGISTICSMOVEMENT tm
JOIN OSUSR_BBQ_TOOLINGLOGISTICSMOVEMENT_TOOLINGITEM tmi 
    ON tm.ID = tmi.MOVEMENTID
JOIN OSUSR_CEQ_TOOLINGITEM ti 
    ON ti.ID = tmi.TOOLINGITEMID
JOIN OSUSR_8DK_JOB j
    ON j.ID = tm.DESTINATIONJOBID AND j.ISDELETED = 0
WHERE ti.INTERNALCOMPANYID = 1
  AND ti.ISDELETED = 0
  AND tm.TYPEID IN (3, 5) -- 3 = Saída, 5 = Transferência
  AND (tm.DESTINATIONJOBID IS NOT NULL OR tm.DESTINATIONWORKERID IS NOT NULL)
  AND tm.STATUSID = 2
  AND j.JOBSTATUSID IN (3, 4, 5)
GROUP BY tm.DESTINATIONJOBID, j.RESPONSIBLEID, ti.NAME, 
         CASE WHEN ti.SERIALNUMBER = '' THEN 'NaoSeriada' ELSE 'Seriada' END
ORDER BY tm.DESTINATIONJOBID, j.RESPONSIBLEID, VolumeSolicitado DESC;