-- TABELA FREQUENCIA GLOBAL DE FERRAMENTAS (Quais ferramentas são mais requisitadas ao todo? -Considerar o volume total como métrica):
-- CASOS:
---- 
SELECT
	ti.NAME,
	tmi.TOOLINGITEMID,
	ROUND(SUM(tmi.QUANTITY), 0) AS VolumeSolicitado
FROM OSUSR_BBQ_TOOLINGLOGISTICSMOVEMENT tm
JOIN OSUSR_BBQ_TOOLINGLOGISTICSMOVEMENT_TOOLINGITEM tmi ON tm.ID = tmi.MOVEMENTID
JOIN OSUSR_CEQ_TOOLINGITEM ti ON ti.ID = tmi.TOOLINGITEMID AND ti.INTERNALCOMPANYID = 1 AND ti.ISDELETED = 0
WHERE tm.STATUSID = 2 
	AND tm.ORIGINWAREHOUSEID IS NOT NULL
GROUP BY tmi.TOOLINGITEMID, ti.NAME
ORDER BY COUNT(tm.ID) desc