-- TABELA FREQUENCIA GLOBAL DE FERRAMENTAS (Quais ferramentas são mais requisitadas ao todo? -Considerar o volume total como métrica):
-- CASOS:
---- 
SELECT
    ti.NAME,
    tmi.TOOLINGITEMID,
    ROUND(SUM(tmi.QUANTITY), 0) AS VolumeSolicitado
FROM OSUSR_BBQ_TOOLINGLOGISTICSMOVEMENT tm
JOIN OSUSR_BBQ_TOOLINGLOGISTICSMOVEMENT_TOOLINGITEM tmi 
    ON tm.ID = tmi.MOVEMENTID
JOIN OSUSR_CEQ_TOOLINGITEM ti 
    ON ti.ID = tmi.TOOLINGITEMID
WHERE ti.INTERNALCOMPANYID = 1
  AND ti.ISDELETED = 0
  AND tm.TYPEID IN (3, 5) -- 3 = Saída, 5 = Transferência
  AND (tm.DESTINATIONJOBID IS NOT NULL OR tm.DESTINATIONWORKERID IS NOT NULL) -- só conta uso real
GROUP BY tmi.TOOLINGITEMID, ti.NAME
ORDER BY VolumeSolicitado DESC;