SELECT
    tm.ID AS MOVEMENTID,
	tt.CODE + '.' + tf.CODE + '.' + sf.CODE AS ToolingCode,
    SUM(tmi.QUANTITY) AS TotalVolume
FROM OSUSR_BBQ_TOOLINGLOGISTICSMOVEMENT tm
JOIN OSUSR_BBQ_TOOLINGLOGISTICSMOVEMENT_TOOLINGITEM tmi 
    ON tm.ID = tmi.MOVEMENTID
JOIN OSUSR_CEQ_TOOLINGITEM ti 
    ON ti.ID = tmi.TOOLINGITEMID
JOIN OSUSR_8DK_JOB j 
    ON j.ID = tm.DESTINATIONJOBID AND j.ISDELETED = 0 AND j.JOBSTATUSID IN (3, 4, 5)
JOIN OSUSR_230_TOOLINGTYPE tt 
	ON tt.ID = ti.TYPEID
JOIN OSUSR_230_TOOLINGFAMILY tf 
	ON tf.ID = ti.FAMILYID
JOIN OSUSR_230_TOOLINGSUBFAMILY 
	sf ON sf.ID = ti.SUBFAMILYID
WHERE ti.INTERNALCOMPANYID = 1
    AND ti.ISDELETED = 0
    AND tm.TYPEID IN (3, 5) -- Exit or Transfer
    AND (tm.DESTINATIONJOBID IS NOT NULL) -- only real use
	AND tmi.CONTAINERID IS NULL
    AND tm.STATUSID = 2
    --AND j.JOBTYPEID != 12 -- Centro de Custos
    GROUP BY tm.ID, tt.CODE + '.' + tf.CODE + '.' + sf.CODE
    ORDER BY MOVEMENTID