-- Query to recommendations based on Jaccard similarity
SELECT
	tm.DESTINATIONJOBID,
	ti.ID AS ToolId,
    ti.NAME AS Tool,
    SUM(tmi.QUANTITY) AS TotalVolume
    FROM OSUSR_BBQ_TOOLINGLOGISTICSMOVEMENT tm
    JOIN OSUSR_BBQ_TOOLINGLOGISTICSMOVEMENT_TOOLINGITEM tmi 
        ON tm.ID = tmi.MOVEMENTID
    JOIN OSUSR_CEQ_TOOLINGITEM ti 
        ON ti.ID = tmi.TOOLINGITEMID
    JOIN OSUSR_8DK_JOB j 
        ON j.ID = tm.DESTINATIONJOBID AND j.ISDELETED = 0 AND j.JOBSTATUSID IN (3, 4, 5)
    WHERE ti.INTERNALCOMPANYID = 1
        AND ti.ISDELETED = 0
        AND tm.TYPEID IN (3, 5) -- Exit or Transfer
        AND (tm.DESTINATIONJOBID IS NOT NULL) -- only real use in jobid
        AND tm.STATUSID = 2
    GROUP BY ti.ID, ti.NAME, tm.DESTINATIONJOBID
	ORDER BY tm.DESTINATIONJOBID;